### ISSUE TITLE
Elevator Pitch

### ISSUE THREAD

**Issue by jesgarsie** [Paula204/ISPP#5]

**Comment by luigilgue** [comment]
Voy a hacer uno que esté solo destinado al trueque por si nos decantamos por esa opción.

**Comment by luigilgue** [comment]
Elevator 1

Hola, mi nombre es NOMBRE APELLIDO1 y en NOMBRE EMPRESA proporcionamos una plataforma online unica y profesional para hacer trueques. ¿Tienes algo por casa que no necesites? Hazle una foto, di que te interesa y ponte en contacto con personas que lo necesiten. NOMBRE EMPRESA, no lo tires ¡Cambialó!

Elevator 2

Buenos dias, mi nombre es NOMBRE APELLIDO1 y en NOMBRE EMPRESA ofrecemos un servicio de intercambio online sencillo y sin complicaciones. Dinos que necesitas ,ofrece algo a cambio y te pondremos en contacto con personas interesadas.  NOMBRE EMPRESA, cambia, disfruta.

Elevator 3

¿Llega el verano y tienes una estufa por casa? ¿Te han regalado tres tostadoras por tu boda? ¿Te compraste una bici y solo la has usado una vez? No te preocupes, entra en DOMINIO EMPRESA, sube una foto, di que te interesa y encuentra personas interesadas cerca de ti. Deja ir lo que no necesites, cambiate a NOMBRE EMPRESA.

**Comment by luigilgue** [comment]
Elevator 4

Buenos dias, mi nombre es NOMBRE APELLIDO1 y en NOMBRE EMPRESA ofrecemos un servicio de intercambio online sencillo y sin complicaciones ¿Llega el verano y tienes una estufa por casa? ¿Te han regalado tres tostadoras por tu boda?  Dinos que necesitas ,ofrece algo a cambio y te pondremos en contacto con personas interesadas. NOMBRE EMPRESA, no lo tires ¡Cambialó!

Elevator 5

Hola, mi nombre es NOMBRE APELLIDO1 y en NOMBRE EMPRESA proporcionamos una plataforma online unica y profesional para hacer trueques. Dinos que necesitas ,ofrece algo a cambio y te pondremos en contacto con personas interesadas.  Deja ir lo que no necesites, cambiate a NOMBRE EMPRESA.

Elevator 6

¿Llega el verano y tienes una estufa por casa? ¿Te han regalado tres tostadoras por tu boda? 
Hola, mi nombre es NOMBRE APELLIDO1 y en NOMBRE EMPRESA proporcionamos una plataforma online unica y profesional para hacer trueques. Dinos que necesitas ,ofrece algo a cambio y te pondremos en contacto con personas interesadas.  NOMBRE EMPRESA, cambia, disfruta.
